name: 'Bump Version'

on:
  push:
    branches:
      - 'main'
      - 'master'

permissions:
    contents: write

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 16
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          minor-wording:  'add,Adds,new,feat,feature'
          major-wording:  'MAJOR,cut-major,major,breaking'
          patch-wording:  'patch,fixes,fix,Chore,chore'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"